[proxies.auth]
target_service = "http://127.0.0.1"
target_port = 9701

[proxies.finance]
target_service = "http://127.0.0.1"
target_port = 9703

[proxies.sales]
target_service = "http://127.0.0.1"
target_port = 9704

[proxies.storage]
target_service = "http://127.0.0.1"
target_port = 9702
